location /rclone/ {
    error_page 401 = @custom_401;
    auth_request /validate;
    auth_request_set $username $upstream_http_username;
    proxy_pass http://127.0.0.1:5572;
    proxy_redirect http://localhost:5572/rclone/ $scheme://$host/rclone/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Remoteuser $username;
    proxy_set_header Connection $connection_upgrade;
    client_max_body_size 10G;
}
