location ~ ^/(download.php|js|css|images|lib) {
    error_page 401 = @custom_401;
    auth_request off;
    auth_request_set $username $upstream_http_username;
    proxy_pass http://127.0.0.1:8080;
    proxy_redirect http://localhost:8080/ $scheme://$host/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Remoteuser $username;
    proxy_set_header Connection $connection_upgrade;
    client_max_body_size 10G;
}

location / {
    if ($arg_s = "download") {
        rewrite ^ /_internal_download last;
    }
    error_page 401 = @custom_401;
    auth_request /validate;
    auth_request_set $username $upstream_http_username;
    proxy_pass http://127.0.0.1:8080;
    proxy_redirect http://localhost:8080/ $scheme://$host/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Remoteuser $username;
    proxy_set_header Connection $connection_upgrade;
    client_max_body_size 10G;
}

location = /_internal_download {
    internal;
    auth_request off;
    proxy_pass http://127.0.0.1:8080/$is_args$args;
    proxy_redirect http://localhost:8080/ $scheme://$host/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    client_max_body_size 10G;
}
